-- card.script

go.property("name", hash(""))
go.property("sprite", hash(""))

local speed = -240


function init(self)
	-- Initialization code here
	msg.post("#sprite", "play_animation", { id = self.name })
	print(self.name)
	--self.sprite

	-- Set the sprite based on the property
	--go.set("#sprite", "image", hash(self.sprite))
end



function update(self, dt)
	local p = go.get_position()
	p.x = p.x + speed * dt
	if p.x < -32 then
		go.delete()
	end
	go.set_position(p)
end
